name: Bug Report - Báo cáo lỗi
description: Create a report to help us improve. - Tạo báo cáo để giúp chúng tôi cải thiện.
title: "[Bug] "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Before filling in this `issue`, please make sure that there are no similar or duplicate `issues` that have been opened.
        Trước khi điền vào `issue` này, vui lòng đảm bảo rằng không có `issue` tương tự hoặc trùng lặp nào đã được mở.

  - type: input
    id: version
    attributes:
      label: Version Details - Thông tin phiên bản
      description: |
        What version of LightNovelReader do you use?
        Bạn đang sử dụng phiên bản LightNovelReader nào?
      placeholder: LightNovelReader version code
    validations:
      required: true

  - type: textarea
    id: exist
    attributes:
      label: Existing behavior - Hành vi hiện tại
      description: |
        Please describe the problem you have encountered carefully.
        Vui lòng mô tả cẩn thận vấn đề bạn gặp phải.
    validations:
      required: true

  - type: textarea
    id: expect
    attributes:
      label: Expected behavior - Hành vi mong đợi
      description: |
        Please describe in detail the results you wish to achieve.
        Vui lòng mô tả chi tiết kết quả bạn mong muốn.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce - Các bước tái hiện
      description: |
        How do you trigger this bug? Please walk us through it step by step.
        Làm thế nào để kích hoạt lỗi này? Vui lòng hướng dẫn chúng tôi từng bước.
    validations:
      required: false

  - type: checkboxes
    id: know
    attributes:
      label: This issue is unique - Issue này là duy nhất
      options:
        - label: I have searched the issue tracker and did not find an issue describing my bug. - Tôi đã tìm kiếm trong trình theo dõi vấn đề và không tìm thấy issue nào mô tả lỗi của mình.
          required: true
