name: Feature request - Yêu cầu tính năng
description: Suggest an idea for this project - Đề xuất ý tưởng mới cho dự án này
title: "[Feature] "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Before filling in this `issue`, please make sure that there are no similar or duplicate `issues` that have been opened.
        Trước khi điền vào `issue` này, vui lòng đảm bảo rằng không có `issue` tương tự hoặc trùng lặp nào đã được mở.

  - type: textarea
    attributes:
      label: What new features do you want? - Bạn muốn tính năng mới nào?
      description: |
        What new feature or change you want? How it improves? Please tell us the requirements is with a clear and detailed description, put your screenshots if possible.
        Bạn muốn tính năng mới nào hoặc thay đổi gì? Nó cải thiện điều gì? Vui lòng mô tả rõ ràng và chi tiết yêu cầu của bạn, đính kèm ảnh chụp màn hình nếu có thể.
    validations:
      required: true

  - type: checkboxes
    id: know
    attributes:
      label: This issue is unique - Issue này là duy nhất
      options:
        - label: I have searched the issue tracker and did not find an issue describing my bug. - Tôi đã tìm kiếm trong trình theo dõi vấn đề và không tìm thấy issue nào mô tả vấn đề của mình.
          required: true
